### ISSUE TITLE
Feature Request: Rotation limit

### ISSUE THREAD

**Issue by santhoshtr** [chanind/curve-matcher#2]
Currently the rotations options rotates the candidate curve in given number of times. So if it is 10, we can expect a rotation in multiples of 36 degrees, if I understand it correctly. But sometimes, what if I want to rote it with in limits, say within 30 degree limit in either directions?

To give an example, a curve like "V", if you rotate in all directions, you can possibly match it with >, <, ^, v etc. But if you limit it to say, 30 degree, you will get matches to V written with limited slanting. This might be the best match than matching with < or >

So, can I request an option to get the above mentioned result?

PS: Thanks a lot for providing this library. I am trying to use this for matching the curves in Malayalam letters.

**Comment by chanind** [comment]
This is a great suggestion! I'll put together a PR with this in the next day or so.
